"""Constants for the Halifax Bar sentiment analysis project."""

BAR_NAMES = {
    "Durty Nelly's",
    "The Lower Deck",
    "The Split Crow",
    "The Old Triangle",
    "The Economy Shoe Shop",
    "Bearly's House of Blues",
    "Gus' Pub",
    "The Seahorse Tavern",
    "The Marquee Ballroom",
    "The Carleton",
    "Stillwell",
    "Good Robot",
    "Propeller Brewing",
    "Garrison Brewing",
    "2 Crows Brewing",
    "Lion's Head Tavern",
    "Freeman's",
    "HFX Sports Bar",
    "Maxwell's Plum",
    "The Bitter End",
    "Antojo Tacos",
    "Battery Park Beer Bar",
    "Niche Lounge",
    "The Loose Cannon",
    "Stubborn Goat Beer Garden",
    "The Press Gang",
    "The Bicycle Thief",
    "Henry House",
    "Rock Bottom Brew Pub",
    "Your Father's Moustache"
}

# Known food specialties and popular menu items for each bar
BAR_SPECIALTIES = {
    "Durty Nelly's": ["Irish pub food", "Fish and Chips", "Shepherd's Pie"],
    "The Lower Deck": ["Pub classics", "Nachos", "Wings"],
    "The Split Crow": ["Pizza", "Wings", "Burgers"],
    "The Old Triangle": ["Irish fare", "Fish and Chips", "Stew"],
    "The Economy Shoe Shop": ["Eclectic menu", "Mediterranean dishes"],
    "Bearly's House of Blues": ["BBQ", "Wings", "Ribs"],
    "Gus' Pub": ["Pizza", "Bar snacks"],
    "Stillwell": ["Craft beer", "Gourmet hot dogs", "Poutine"],
    "Good Robot": ["Bar snacks", "Food truck collaborations"],
    "Lion's Head Tavern": ["Pub food", "Wings", "Burgers"],
    "Freeman's": ["Pizza", "Garlic fingers"],
    "HFX Sports Bar": ["Wings", "Burgers", "Nachos"],
    "Maxwell's Plum": ["Wings", "Burgers", "Pub fare"],
    "The Bitter End": ["Tapas", "Small plates"],
    "Antojo Tacos": ["Mexican food", "Tacos", "Margaritas"],
    "Battery Park Beer Bar": ["Craft beer", "Gourmet burgers"],
    "The Loose Cannon": ["Scottish pub food", "Fish and Chips"],
    "Stubborn Goat Beer Garden": ["Gastropub fare", "Shared plates"],
    "The Press Gang": ["Seafood", "Fine dining"],
    "Henry House": ["British pub food", "Sunday roast"],
    "Rock Bottom Brew Pub": ["Pub food", "House-brewed beer"],
    "Your Father's Moustache": ["Wings", "Pub classics", "Rooftop patio food"]
} 